.chart:
  stage: chart
  variables:
    CHART_NAME: ""
  only:
    - tags
  image: harbor-gn2.cicd.s15m.nl/ictu-devops-pub/library/helm-toolbox:latest
  script:
    - echo charting ${CHART_NAME}
    - helm package ./deployment/helm/${CHART_NAME}/ --version ${CI_COMMIT_TAG}
    - mkdir -p ./generated
    - mv ./${CHART_NAME}-${CI_COMMIT_TAG}.tgz ./generated
    - PASSWORD_DECODED=$(echo ${HARBOR_ROBOT_SECRET} | base64 -d)
    - echo ${PASSWORD_DECODED} | helm registry login -u ${HARBOR_ROBOT_NAME} harbor-gn2.cicd.s15m.nl --password-stdin
    - helm push ./generated/${CHART_NAME}-${CI_COMMIT_TAG}.tgz oci://harbor-gn2.cicd.s15m.nl/ictu-devops-charts
  when: on_success
